#Set working directory
workdir: "$HOME/scratch/admixture_analysis"

#Set sample names
SAMPLES: ["BH2_MHL", "BH2_FBL", "BH2_F1_1", "BH2_F1_2", "BH2_F2_1", "BH2_F2_2", "BH2_F3_1", "BH2_F3_2", "BH4_F1_1", "BH8_MHL", "BH8_FBL", "BH10_F1_1", "BH10_F1_2", "BH10_F2_1", "BH10_F2_2", "BH10_F3_1", "BH10_F3_2"]

#Set reference genome name
GENOME: "genomes/p_humanus_reference.fa"

#Define important paths
ADAPTERS: "/storage/work/cxb585/bin/Trimmomatic-0.36/adapters/TruSeq3-PE.fa"
BAMTOOLS: "/storage/work/cxb585/bin/bamtools/bin/bamtools-2.4.1" 
BWA: "/storage/work/cxb585/bin/bwa-0.7.16a/bwa"
GATK: "/storage/work/cxb585/bin/GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar"
PDGSPIDER: "/storage/work/cah422/bin/PGDSpider_2.1.1.3/PGDSpider2-cli.jar"
PICARD: "/storage/work/cxb585/bin/picard-2.10.10/picard.jar"
SAMTOOLS: "/storage/work/cxb585/bin/samtools-1.5/bin/samtools"
TRIMMOMATIC: "/storage/work/cxb585/bin/Trimmomatic-0.36/trimmomatic-0.36.jar"

#Select modules to load
MODULES: ["bamtools", "bcftools", "bwa", "gatk", "picard", "python", "samtools", "trimmomatic", "vcftools"]
