#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=36:00:00
#PBS -M coalhende@gmail.com
#PBS -N cat_files_R2
#PBS -m abe

# -------------------------------------------------- #
#Cat sequence files
# -------------------------------------------------- #

#move to correct directory
cd ~/scratch/admixture_analysis/data/

#Cat R2
for file in `cat sample_names.txt`; do gzip -d -c --force raw_reads/L006_R2/${file}* raw_reads/L007_R2/${file}* | cat > ${file}_R2.fastq; gzip ${file}_R2.fastq; done

exit;
