#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=4:00:00
#PBS -M coalhende@gmail.com
#PBS -N cat_reads
#PBS -m abe

# -------------------------------------------------- #
#cat reads together from different sequencing lanes
# -------------------------------------------------- #

#Move to correct directory
cd /storage/home/cah422/scratch/admixture_anaysis/data/new_data

#cat R1
for i in $(cat sample_names.txt); do cat ./L006_R1/${i}* ./L007_R1/${i}* > ./R1/${i}_R1.fastq.gz; done

#cat R2
for i in $(cat sample_names.txt); do cat ./L006_R2/${i}* ./L007_R2/${i}* > ./R2/${i}_R2.fastq.gz; done

exit;
