#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -M coalhende@gmail.com
#PBS -N cat_files_R2
#PBS -m abe

# -------------------------------------------------- #
#format reference genome
# -------------------------------------------------- #

#load modules
module load bwa samtools picard

#move to correct directory
cd ~/scratch/NGS_map-snakemake/genomes/

#index reference
bwa index -a bwtsw p_humanus_reference.fa

#generate index file
samtools faidx p_humanus_reference.fa

#generate sequencing directory
java -jar /storage/work/cxb585/bin/picard-2.10.10/picard.jar CreateSequenceDictionary REFERENCE=p_humanus_reference.fa OUTPUT=p_humanus_reference.dict  

exit;
