#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=4:00:00
#PBS -M coalhende@gmail.com
#PBS -N index_reference
#PBS -m abe
#PBS -e /storage/home/cah422/scratch/admixture_analysis/pbs_output/${PBS_JOBNAME}.e${PBS_JOBID}.${PBS_ARRAYID}
#PBS -o /storage/home/cah422/scratch/admixture_analysis/pbs_output/${PBS_JOBNAME}.o${PBS_JOBID}.${PBS_ARRAYID}

# -------------------------------------------------- #
#Index reference genome using BWA
# -------------------------------------------------- #

#Move to correct directory
cd /storage/home/cah422/scratch/admixture_anaysis

#Set variables
GENOME=p_humanus_reference.fa

#Index genome
sh ./scripts/index_reference_genome.sh $GENOME

exit;
