#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=4:00:00
#PBS -M coalhende@gmail.com
#PBS -N index_bam
#PBS -m abe
#PBS -e /storage/home/cah422/scratch/admixture_analysis/pbs_output/${PBS_JOBNAME}.e
#PBS -o /storage/home/cah422/scratch/admixture_analysis/pbs_output/${PBS_JOBNAME}.o

# -------------------------------------------------- #
#Index mapped reads .bam
# -------------------------------------------------- #

#Move into correct directory
cd /storage/home/cah422/scratch/admixture_anaysis/

#Set variables
MAPPED_READS=CAH9.PE.bwa.p_humanus_reference.fa.sam.bam

#Call sam_to_bam.sh
sh scripts/sam_to_bam.sh $MAPPED_READS

exit;
