#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=24:00:00
#PBS -M coalhende@gmail.com
#PBS -N snakemake_run
#PBS -m abe

# -------------------------------------------------- #
#Cat sequence files
# -------------------------------------------------- #

#move to correct directory
cd ~/scratch/NGS_map-snakemake/

#run snakemake
module load python
snakemake --unlock
snakemake --ri -j 7 --cluster "qsub -A ghp3_a_g_sc_default -l walltime=24:00:00,nodes=1:ppn=8"

exit;
