#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=4:00:00
#PBS -M coalhende@gmail.com
#PBS -N sort_bam
#PBS -m abe
#PBS -e /storage/home/cah422/scratch/admixture_analysis/pbs_output/${PBS_JOBNAME}.e${PBS_JOBID}.${PBS_ARRAYID}
#PBS -o /storage/home/cah422/scratch/admixture_analysis/pbs_output/${PBS_JOBNAME}.o${PBS_JOBID}.${PBS_ARRAYID}

# -------------------------------------------------- #
#Sort mapped reads .bam
# -------------------------------------------------- #

#Move to correct directory
cd /storage/home/cah422/scratch/admixture_anaysis 

#Define variables
MAPPED_READS=CAH9.PE.bwa.p_humanus_reference.fa.sam.bam

#Call sort_bam.sh on mapped reads .bam
sh scripts/sort_bam.sh $MAPPED_READS

exit;
