#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=4:00:00
#PBS -M coalhende@gmail.com
#PBS -N trim_raw_reads
#PBS -m abe
#PBS -e /storage/home/cah422/scratch/admixture_analysis/pbs_output/${PBS_JOBNAME}.e${PBS_JOBID}.${PBS_ARRAYID}
#PBS -o /storage/home/cah422/scratch/admixture_analysis/pbs_output/${PBS_JOBNAME}.o${PBS_JOBID}.${PBS_ARRAYID}

# -------------------------------------------------- #
#Trim raw reads using trimmomatic
# -------------------------------------------------- #

#Move to correct directory
cd /storage/home/cah422/scratch/admixture_anaysis

##Set variable names
IND_ID=CAH9

#Run trimmomatic
sh scripts/trim_reads.sh $IND_ID $IND_ID

exit;  
